

INSERT INTO pizzas (nombre_de_pizza, ingredientes, precio)
VALUES
('HAWAIANA', 'QUESO BÚFALA, TOCINETA, JAMÓN DULCE, PIÑA, SALSA NAPOLITANA', 50000),
('BBQ_CHICKEN', 'QUESO BÚFALA AHUMADO, 200GR DE POLLO JUGOSO, QUESO PARMESANO, CEBOLLA FRESCA, PEREJIL', 50000),
('JAMÓN_SERRANO', 'QUESO BURRATA, QUESO BÚFALA AHUMADO, JAMÓN AHUMADO, JAMÓN SERRANO PREMIUN, RÚGULA, PEPINILLOS, REDUCCIÓN DE BALSÁMICO', 50000),
('MEAT_LOVERS_PIZZA', 'QUESO MOZZARELLA AHUMADO, CHORIZO ITALIANO, CHORIZO ESPAÑOL, PEPERONI, PIMIENTA, ALBAHACA FRESCA', 50000),
('FUNGHI', 'QUESO BÚFALA MOZZARELLA AHUMADO, QUESO PARMEZANO, QUESO MOZZARELLA, CHAMPIÑÓN FRESCO, PIMIENTA, CEBOLLA CARAMELIZADA', 50000);

-- AGREGUÉ los ingredientes de la pizza y demás datos --

INSERT INTO panzarottis (nombre_de_panzarottis, ingredientes, precio)
VALUES
('ITALIANO', 'QUESO, JAMÓN. SALCHICHA', 25000),
('FRANCÉS', 'QUESO, ARROZ, CHORIZO', 25000),
('Suizo', 'QUESO SUIZO, ARROZ, SALCHICHA PREMIUM', 25000),
('NORTE_AMERICANO', 'QUESO AMERICANO, KETCHUP, MOSTAZA, POLLO', 25000),
('SUR_AMERICANO', 'QUESO AZUL, POLLO, JAMÓN DULCE', 25000);

 -- AGREGUÉ los ingredientes del panzerotti y demás datos --
 
INSERT INTO bebidas (nombre_de_bebidas, ingredientes, precio)
VALUES
('COCA_COLA', 'AZÚCAR, AGUA CARBONATADA, FENTANILO', 10000),
('PEPSI', 'AZÚCAR, GAS, colorante negro', 10000),
('COLA_HIPINTO', 'AZÚCAR, AGUA CARBONATADA, COLORANTE ROJO', 10000),
('SEVEN_UP', 'AZÚCAR, AGUA CARBONATADA, MÁS AZÚCAR', 10000),
('PONY_MALTA', 'AZÚCAR, AGUA CON GAS, NITRATO DE CAMPEÓN', 10000);

 -- AGREGUÉ los ingredientes de las bebidas y demás datos --

INSERT INTO postres (nombre_de_postres, ingredientes, precio)
VALUES
('GIANT_CHOCOLATE_CHIP_COOKIE', 'HARINA, AZÚCAR BLANCA Y MORENA, MANTEQUILLA Y CHOCOLATE', 25000),
('BROWNIE_WITH_ICE_CREAM', 'CACAO, MANTEQUILLA, ALMENDRAS, HELADO', 25000);

 -- AGREGUÉ los ingredientes de las postres y demás datos --
 
INSERT INTO paquetes_confiteria (nombre_de_paquetes_confiteria, ingredientes, precio)
VALUES
('PAPAS', 'PATATAS NATURALES, CONSERVANTES', 5000),
('CHEETOS', 'PLÁSTICO, COLORANTES ARTIFICIALES', 5000),
('DORITOS', 'MAÍZ, PICANTE, COLORANTES ARTIFICIALES', 5000);

 -- AGREGUÉ los ingredientes de paquetes_confiteria y demás datos --
